### ISSUE TITLE
How to split the data?

### ISSUE THREAD

**Issue by TysonYu** [Yale-LILY/ConvoSumm#1]
Hi Alexander,

Thanks for publishing the dataset. After downloading the data, do you know how to split the data to train/valid/test for a fair comparison with your experimental results?

Tyson

**Comment by Alex-Fabbri** [comment]
Hi Tyson, 

Thank you for your interest in our work! We provide lists of the IDs and their split in a .json file which correspond to the example_id in the jsonl file. For example, data-non-processed/nyt.ids.json has lists of train, val, and test ids which can be matched in data-non-processed/nyt.jsonl.

**Comment by TysonYu** [comment]
Thanks for your clear explanation!
