### ISSUE TITLE
accessing model checkpoints

### ISSUE THREAD

**Issue by lakshmi-imrsv** [Yale-LILY/ConvoSumm#2]
Hi , I am trying to replicate your project.As a first step I am trying to download model checkpoints using awscli. I am using aws for the first time and I am having an error " fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied " . Can you help me how to solve this?I created a Free tier account with aws.
Is the model checkpoints are available to download using google drive link also?

**Comment by Alex-Fabbri** [comment]
Hi, 
The checkpoints are not available using the google drive link. For awscli, did you run `aws configure` and fill in the access key credentials (see [this page](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html) for details)? If you haven't, that's probably cause of this error.

**Comment by lakshmi-imrsv** [comment]
Hi
Thanks for replying. I have run the acess key and aws configure  and still encountered the same problem.I am interested in running the long former model.In the script for running longformer model  I could see the model as  "converted-model-bart-large-cnn-long-16384".Is it the same model  we obtain after training BART using fairseq(  https://github.com/Yale-LILY/ConvoSumm/tree/master/code#bart )?

**Comment by yihui-he** [comment]
@Alex-Fabbri  same error 
```
$ aws s3 cp --recursive s3://convosumm/checkpoints/ ./checkpoints
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by Alex-Fabbri** [comment]
Apologies for the inconvenience - I've uploaded the checkpoints [here](https://drive.google.com/drive/folders/1y1p2JCNDjhPmbuOE0skYTojlaXvpyErg?usp=sharing).

**Comment by evan-person** [comment]
Thank you for uploading model checkpoints. Will you include the Longformer checkpoints at this location in the future?

**Comment by Alex-Fabbri** [comment]
Yes I meant to upload all models - there was an error in uploading which I will resolve.

**Comment by evan-person** [comment]
No problem. Thank you again for providing the models.

**Comment by Alex-Fabbri** [comment]
Sorry for the long delay! I'll follow up with the checkpoints soon.

**Comment by Alex-Fabbri** [comment]
Errors related to permissions on the S3 bucket have been resolved. Since you can download the checkpoints without an AWS account using ` --no-sign-request` appended to the awscli request, I won't be updating the Google Drive links for now.
